# Generated by Django 4.0.6 on 2022-08-01 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autenticacao', '0003_pessoa_delete_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
